name: Links (Fail Fast)

on:
  push:
  pull_request:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.4.1
        with:
          fail: true
          args: "--base-url https://hybrid-cloud-patterns.io/ --verbose --no-progress './**/*.md' './**/*.html'"
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
