name: Auto Comment
on: pull_request
jobs:
  autocomment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: exercism/pr-commenter-action@v1.4.0
        with:
          github-token: "${{ github.token }}"
          config-file: ".github/pr-commenter.yml"
